/* Auto-generated by tools/bump_version.py - do not edit manually */
#ifndef ASSOCTREE_VERSION_H
#define ASSOCTREE_VERSION_H

#define ASSOCTREE_VERSION_MAJOR 1
#define ASSOCTREE_VERSION_MINOR 0
#define ASSOCTREE_VERSION_PATCH 1
#define ASSOCTREE_VERSION_STR "1.0.1"

#endif // ASSOCTREE_VERSION_H
