/* Auto-generated by tools/bump_version.py - do not edit manually */
#ifndef ASSOCTREE_VERSION_H
#define ASSOCTREE_VERSION_H

#define ASSOCTREE_VERSION_MAJOR 0
#define ASSOCTREE_VERSION_MINOR 1
#define ASSOCTREE_VERSION_PATCH 2
#define ASSOCTREE_VERSION_STR "0.1.2"

#endif // ASSOCTREE_VERSION_H
